### user Api List

### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
  
"fname" : "Surendra",
"lname" : "KC", 
"dob": "2021-10-10", 
"email": "tesst2@a.com",
"password": "12345s", 
"phone": "0411111111", 
"address": "10 George st, Sdyeny, 2000", 
"gender": "male" 


}

### user email verification
POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp":"04330580",
    "email":"tesst2@a.com"
}



###Category API List

### find category
GET http://localhost:8000/api/v1/category

### create category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name":"Home wdasssre",
    "parentCat":null
}

###update the category
PATCH http://localhost:8000/api/v1/category/616e010445cf925f31f446f0
Content-Type: application/json

{
  "name":"Kitchen Wdfdsdsfare",
  "parentCat":"kitcdsdfdshen"
}

### update category
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "_id":"6171e98805a12509bc643110",
  "name":"Assr",
  "parentCat":""
}


###log in
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "email":"tesst2@a.com",
  "password":"12345s"
}


### delete category
DELETE http://localhost:8000/api/v1/category/6171e96d05a12509bc643109